---
title: "Example for Survival Data -- Breast"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
params:
  seed: !r 29221
--- 

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 7
)

# Load do package
devtools::load_all()

ggplot2::theme_set(ggplot2::theme_minimal())
.Last.value <- futile.logger::flog.layout(futile.logger::layout.format('[~l] ~m'))

.Last.value <- loose.rock::base.dir(tempdir())
.Last.value <- loose.rock::show.message(FALSE)
```

# Required Packages

```{r libraries}
library(futile.logger)
library(ggplot2)
library(reshape2)
library(dplyr)
library(survival)
library(loose.rock)
library(glmnet)
```

```{r, eval=FALSE}
library(glmSparseNet)
```

# Load data

```{r data, echo=FALSE}
# download data package with TCGA data
biocLite('https://github.com/averissimo/tcga.data/releases/download/2017.07.21-prad/prad.data_1.0.tar.gz')

# load package
library(brca.data)

my.data <- prepare.tcga.survival.data(project           = 'brca', 
                                      tissue.type       = 'primary.solid.tumor', 
                                      handle.duplicates = 'keep_first', 
                                      coding.genes      = TRUE)

# Using only a subset of genes previously selected to keep this short example.

set.seed(params$seed)
small.subset <- c('ENSG00000110448', 'ENSG00000124449', 'ENSG00000103494', 
                  'ENSG00000172053', 'ENSG00000136758', 'ENSG00000051382', 
                  'ENSG00000128655', 'ENSG00000100368', 'ENSG00000115884', 
                  'ENSG00000133119', 'ENSG00000179363', 'ENSG00000091106', 
                  'ENSG00000178403', 'ENSG00000066422', sample(colnames(my.data$xdata), 100))
xdata <- my.data$xdata[,small.subset]
ydata <- my.data$ydata
```

```{r, eval=FALSE}
# save data in package
sample.BRCA.survival <- list(xdata = xdata, ydata = ydata)
devtools::use_data(sample.BRCA.survival, overwrite = TRUE)
```

```{r, include=FALSE}
data("sample.BRCA.survival", package = 'glmSparseNet')
xdata <- sample.BRCA.survival$xdata
ydata <- sample.BRCA.survival$ydata
```

# Fit models

```{r fit.show}
fitted <- network.cv.glmnet(xdata, Surv(ydata$time, ydata$status), network = 'correlation', family = 'cox', nlambda = 1000)
```

# Results of Cross Validation

```{r results}
plot(fitted)
```

## Using lambda.min taken from cross validation

```{r, echo=FALSE}
top.coefs <- coef(fitted, s = 'lambda.min')
coefs.v <- as.vector(top.coefs)
names(coefs.v) <- rownames(top.coefs)
flog.info('Non-zero coefficients:', coefs.v[coefs.v != 0], capture = T)
```

### Hallmarks of Cancer

```{r, echo=FALSE}
names.df <- gene.names(names(coefs.v[coefs.v != 0]))
all.hallmarks <- hallmarks(names.df$external_gene_name)

all.hallmarks$heatmap
```

### Survival curves and Log rank test

```{r, echo=FALSE}
glmSparseNet::draw.kaplan(as.vector(coefs.v), xdata, ydata, plot.title = 'Full dataset', legend.outside = F)
```

