---
title: "Analyze full network"
author: "André Veríssimo"
date: "`r Sys.Date()`"
output:
  #rmarkdown::html_vignette:
  html_document:
    toc: true
    self_contained: true
    number_sections: true
    fig_width: 10
#vignette: >
#  %\VignetteIndexEntry{Vignette Title}
#  %\VignetteEngine{knitr::rmarkdown}
#  %\VignetteEncoding{UTF-8}
params:
  project: 'brca' # skcm prad brca
  tissue: 'primary.solid.tumor' # primary.solid.tumor metastatic solid.tissue.normal
  degree.correlation: 'pearson'
  #
  degree.type: "sparsebn" # covariance, correlation sparsebn
  probs: !r c(seq(0,1,0.05), .975, .99, .999, .9999, .99999)
  #
  seed: !r 1985# 2017
  mc.cores: !r 5
---

```{r markdown.generation, eval=FALSE, include=FALSE}
rm(list = ls())
gc(reset = TRUE)
gc(reset = TRUE)
rmarkdown::render('full.network.analysis.Rmd', output_file = 'Network.Analysis.Covariance.BRCA.html',
                  params = list(degree.type = 'covariance', project = 'brca', params = c(seq(0,1,0.05), .975, .99, .999, .9999, .99999)))
#
rm(list = ls())
gc(reset = TRUE)
gc(reset = TRUE)
rmarkdown::render('full.network.analysis.Rmd', output_file = 'Network.Analysis.Correlation.BRCA.html',
                  params = list(degree.type = 'correlation', project = 'brca'), params = c(seq(0,1,0.05), .975, .99, .999, .9999, .99999))
rm(list = ls())
gc(reset = TRUE)
gc(reset = TRUE)
```


```{r setup, include=FALSE}
# ComBat(matrix and category_id)
# plotMDS(matrix and some color stuff)
# inSilicoDB is good to understand that and validate results
knitr::opts_chunk$set(echo = TRUE, collapse = TRUE, tidy = TRUE)
library(futile.logger)
library(parallel)
library(glmnet)
library(ggplot2)
library(reshape2)
library(survival)
library(brca.data)
library(Vennerable)
library(limma)
library(tidyverse)
library(forcats)
library(brca.data)

devtools::install_github('averissimo/loose.rock')
library(loose.rock)
#
devtools::load_all()
#
.Last.value <- loose.rock::base.dir(path = '/ssd_home/averissimo/work/rpackages/network.cox-cache')
.Last.value <- loose.rock::show.message(TRUE)
.Last.value <- flog.layout(layout.format('[~l] ~m'))
.Last.value <- flog.appender(appender.tee('logger.txt'))
theme_set(theme_minimal())
#
# sparsebn
installed.ccdr <- devtools::install_github('averissimo/ccdrAlgorithm')
if (installed.ccdr) { devtools::install_github('averissimo/sparsebn', force = T) }
library(sparsebn)
library(sparsebnUtils)
```

# Parameters

```{r params, echo=FALSE}
max.chars <- max(sapply(names(params), nchar))
for (ix.names in sort(names(params))) {
  prefix <- paste(array(' ', max.chars - nchar(ix.names)), collapse = '')
  if (is.vector(params[[ix.names]]) && length(params[[ix.names]]) == 1) {
    if (is.character(params[[ix.names]])) {
      flog.info('  %s%s: %s', prefix, ix.names, params[[ix.names]])
    }  else if (is.integer(params[[ix.names]])) {
      flog.info('  %s%s: % 11d', prefix, ix.names, params[[ix.names]])
    } else {
      flog.info('  %s%s: % 11.3f', prefix, ix.names, params[[ix.names]])
    }
  } else if (is.vector(params[[ix.names]])) {
    flog.info('  %s%s: %s', prefix, ix.names, paste(params[[ix.names]], collapse = ', '))
  } else {
    flog.info('  %s%s: (i do not know how to display this)', prefix, ix.names)
  }
}
```

# Load and normalize data

Description of data

```{r data.desc, echo=FALSE}
package.name <- paste0(params$project, '.data')
data("fpkm.per.tissue", package = package.name)
flog.info('Loading data from %s package', package.name)
flog.info('Types of tissue:\n * %s', paste(sprintf('%s (%d)', names(fpkm.per.tissue), sapply(fpkm.per.tissue, ncol)), collapse = '\n * '))
rm(fpkm.per.tissue)
```

```{r}
my.data <- loose.rock::run.cache(prepare.tcga.survival.data, 'brca', 'primary.solid.tumor', 'keep_first',
                                #
                                cache.prefix = 'tcga-data')
#
xdata     <- my.data$xdata.raw
ydata     <- my.data$ydata
#
# keep only coding protein
if (params$degree.type == 'sparsebn') {
  coding <- run.cache(coding.genes, cache.prefix = 'coding.genes')
  xdata <- xdata[,colnames(xdata) %in% coding$ensembl_gene_id]
  xdata.digest.cache <- digest.cache(xdata)
} else {
  # keep full dataset
  xdata.digest.cache <- my.data$xdata.raw.digest 
}
#
ydata.digest.cache <- my.data$ydata.digest
#
rm(my.data)
```

```{r}
flog.info('Number of:')
flog.info('  *    variables: %d', ncol(xdata))
flog.info('  * observations: %d', nrow(xdata))
```

```{r, eval=FALSE}
ix.dag <- sapply(names(my.dag$edges), function(ix) { return(length(my.dag$edges[[ix]]) != 0) })

edges <- sapply(seq_along(my.dag$edges), function(ix) {
  el <- my.dag$edges[[ix]]
  return(as.vector(t(cbind(array(ix, length(el)), el))))
})

edges.vec <- unlist(edges)

igraph::plot.igraph(edges.vec)

edgeList.short <- my.dag$edges[1:10]
class(edgeList.short) <- class(my.dag$edges)


sparsebn::plotDAG(my.dag$edges)
```


## Build network

```{r build.network, echo=FALSE}
if (params$degree.type == 'covariance') {
  my.network <- abs(cov.parallel(xdata, method = 'pearson', 
    base.dir = '../../network.cox-cache',
    build.matrix = T,
    n.cores = params$mc.cores,
    show.message = F
  ))
} else if (params$degree.type == 'correlation') {
  my.network <- abs(cor.parallel(xdata, method = 'pearson', 
    build.matrix = T,
    n.cores = params$mc.cores,
    show.message = F
  ))
} else if (params$degree.type == 'sparsebn') {
  lambdas <- sparsebnUtils::generate.lambdas(nrow(xdata), lambdas.length = 50)
  sparse.xdata <- loose.rock::run.cache(sparsebnData, xdata, levels = NULL, ivn = NULL, type = 'continuous', 
                                       cache.prefix = 'sparsebn.data')
  #
  dag <- loose.rock::run.cache(sparsebn::estimate.dag, sparse.xdata, lambdas = lambdas, upperbound = ncol(xdata) * 2,
                              cache.prefix = 'dag')
  dag.params <- run.cache(sparsebnUtils::estimate.parameters, dag, data = sparse.xdata, verbose = T, cache.prefix = 'dag.params')
  my.dag <- select(dag, lambda = lambdas[length(lambdas)])
  my.network <- abs(dag.params[[50]]$coefs@x)
  my.network.full <- abs(dag.params[[50]]$coefs)
} else {
  stop('Error on degree type')
}
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
# create sha256 digest to reuse and accelerate cache
network.digest <- loose.rock::digest.cache(my.network)
```

```{r, echo=FALSE, include=FALSE}
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
quantile.abs <- loose.rock::run.cache(quantile, my.network, probs = sort(params$probs),
                                     #
                                     cache.digest = list(network.digest),
                                     cache.prefix = 'quantile')
result <- quantile.abs
save(result, file = sprintf('../saves/quantile.abs-%s.RData', params$degree.type))
#
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
mean.abs <- loose.rock::run.cache(mean, my.network,
                                 #
                                 cache.digest = list(network.digest),
                                 cache.prefix = 'quantile')
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
max.abs <- loose.rock::run.cache(max, my.network,
                                #
                                cache.digest = list(network.digest),
                                cache.prefix = 'max')
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
.Last.value <- gc(reset = TRUE, verbose = FALSE)
min.abs <- loose.rock::run.cache(min, my.network,
                                #
                                cache.digest = list(network.digest),
                                cache.prefix = 'min')
#
```

## Statistical description

### Summary

```{r summary, echo=FALSE}
flog.info('Min: %g -- Mean: %g -- Median: %g-- Max: %g', min.abs, mean.abs, quantile.abs[['50%']], max.abs)
```

### Quantiles

```{r, echo=FALSE}
data.frame(quantile.abs)
```

## Weighted Degree

- builds plots

```{r plots.gen, echo=FALSE, include=FALSE}
#
my.seq <- seq_along(quantile.abs)
result <- mclapply(my.seq, function(ix.i) {
  ix <- quantile.abs[ix.i]
  #
  if (params$degree.type == 'covariance') {
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    weighted <- degree.cov.weighted(xdata, method = params$degree.correlation, cutoff = ix,
                                    consider.unweighted = FALSE,
                                    n.cores = 1,
                                    show.message = FALSE)
    #
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    weighted.non <- degree.cov.weighted(xdata, method = params$degree.correlation, cutoff = ix,
                                        consider.unweighted = TRUE,
                                        n.cores = 1,
                                        show.message = FALSE)
  } else if (params$degree.type == 'correlation') {
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    weighted <- degree.cor.weighted(xdata, method = params$degree.correlation, cutoff = ix,
                                    consider.unweighted = FALSE,
                                    n.cores = params$mc.cores,
                                    show.message = FALSE)
    #
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    weighted.non <- degree.cor.weighted(xdata, method = params$degree.correlation, cutoff = ix,
                                        consider.unweighted = TRUE,
                                        n.cores = params$mc.cores,
                                        show.message = FALSE)
  } else if (params$degree.type == 'sparsebn') {
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    
    weighted <- degree.sparsebn.weighted(xdata, cutoff = ix,
                                    consider.unweighted = FALSE,
                                    show.message = FALSE)
    
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    .Last.value <- gc(reset = TRUE, verbose = FALSE)
    weighted.non <- degree.sparsebn.weighted(xdata, cutoff = ix,
                                        consider.unweighted = TRUE,
                                        show.message = FALSE)
    
    my.graph <- run.cache(sparsebnUtils::to_igraph, my.dag)
    components.w <- igraph::count_components(my.graph$edges, mode = 'weak')
    components.s <- igraph::count_components(my.graph$edges, mode = 'strong')
  }  
  #
  #

  plot.w <- ggplot(melt(weighted)) +
      geom_freqpoly(aes(value, color = loose.rock::my.colors(1)), bins = 200) +
      theme_minimal() + theme(legend.position = 'none') + 
      theme(legend.position = 'none') +
      #scale_x_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000, 10000, 55000)) +
      ggtitle('Weighted Degree distribution ', 
              subtitle = sprintf('cutoff: %g (quantile %s)', ix, names(ix))) +
      scale_y_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000, 10000, 30000)) +
      ylab('Frequency (log10 scale)') +
      xlab('Degree')
  
  #
  plot.u <- ggplot(melt(weighted.non)) +
      geom_freqpoly(aes(value, color = loose.rock::my.colors(1)), bins = 200) +
      theme_minimal() + theme(legend.position = 'none') + 
      theme(legend.position = 'none') +
      #scale_x_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000, 10000, 55000)) +
      ggtitle('Un-Weighted Degree distribution ', 
              subtitle = sprintf('cutoff: %g (quantile %s)', ix, names(quantile.abs)[ix.i])) +
      scale_y_continuous(trans = 'log10', breaks = c(1, 10, 100, 1000, 10000, 30000)) +
      ylab('Frequency (log10 scale)') +
      xlab('Degree')
  #
  network.info <- list(nodes        = length(weighted.non), 
                       disconnected = sum(weighted.non == 0), 
                       connected    = sum(weighted.non != 0),
                       edges        = sum(weighted.non),
                       max.edges    = length(weighted.non)^2,
                       components.weak = components.w,
                       components.strong = components.s)
  #
  return(list(weighted = plot.w, unweighted = plot.u, network.info = network.info, quantile = names(quantile.abs)[ix.i]))
}, mc.cores = 1, mc.allow.recursive = FALSE, mc.cleanup = TRUE, mc.preschedule = FALSE)
```

- shows plots

```{r plot.show, echo=FALSE}
for (ix in seq_along(result)) {
  flog.info('Network info for %s quantile:', result[[ix]]$quantile)
  flog.info('  * nodes: %d', result[[ix]]$network.info$nodes)
  flog.info('    * disconnected: %d', result[[ix]]$network.info$disconnected)
  flog.info('    *    connected: %d', result[[ix]]$network.info$connected)
  flog.info('  * edges: %g', result[[ix]]$network.info$edges)
  flog.info('    * out of possible: %g', result[[ix]]$network.info$max.edges)
  
  if (params$degree.type == 'sparsebn') {
    flog.info('Graph components:')
    flog.info('  *   weak: %d', result[[ix]]$network.info$components.weak)
    flog.info('  * strong: %d', result[[ix]]$network.info$components.strong)
  }
  #
  multiplot(plotlist = list(result[[ix]]$weighted, result[[ix]]$unweighted), ncol = 2)
}
````
