---
title: "retro-engineer"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(reshape2)
library(ggplot2)
library(futile.logger)
library(dplyr)
.Last.value <- flog.layout(layout.format('~m'))
theme_set(theme_minimal())
```

## Load data

```{r}
degree.cutoff <- 0.05

load(sprintf('/home/averissimo/work/rpackages/brca.analysis/data/degree-%.6f.RData', degree.cutoff))

degree.old_0.5 <- degree
rm(degree)

load(sprintf('../saves/degree-covariance-0.00000.RData', degree.cutoff))
#load(sprintf('../saves/degree-%.5f.RData', degree.cutoff))

degree.new_0.5 <- degree
rm(degree)

set.seed(1985)
random.sample <- sample(seq_along(degree.old_0.5), 30)
```


```{r}
qplot(degree.old_0.5, bins = 100)
qplot(degree.new_0.5, bins = 100)
```


### Compare function

```{r, message=FALSE}
compare.data <- function(old, new, show.ixs = sample(seq_along(old), 15) ) {
  
  df <- data.frame(ix = seq_along(old), old = old, new = new, diff = abs(old - new))
  df.melt <- melt(df, id.vars = 'ix')
  
  flog.info('Old:', summary(old), capture = T)
  flog.info('New:', summary(new), capture = T)
  
  print(
    ggplot(filter(df.melt, value > 0)) + geom_freqpoly(aes(value), bins = 500) +
      scale_y_continuous(trans = 'log10') + ylab(label = 'Count (log10)') +
      facet_wrap(~ variable, ncol = 1)
    )
  
  print(
    ggplot(data.frame(new = new, old = old)) + 
      geom_point(aes(new, old, color = abs(old - new)), size = 0.1, alpha = .3) +
      scale_color_gradient(low = "#00ff00", high = "#ff0000") +
      theme(legend.position = 'none')
  )
  
  print(
    ggplot(data.frame(new = sort(new), old = sort(old))) + 
      geom_point(aes(new, old, color = abs(old - new)), size = 0.1, alpha = .3) +
      scale_color_gradient(low = "#00ff00", high = "#ff0000") +
      theme(legend.position = 'none')
  )
  
  print(
    ggplot(melt(data.frame(ix = seq_along(show.ixs), new = old[show.ixs], old = new[show.ixs]), id.vars = 'ix')) + 
      geom_point(aes(ix, value, color = variable, shape = variable)) + 
      geom_line(aes(ix, value, color = variable)) + 
      scale_y_continuous(trans = 'log10') + ylab('Value (log10)') +
      scale_x_continuous(labels = show.ixs, breaks = seq_along(show.ixs)) +
      theme(axis.text.x = element_text(angle = 45, hjust = 1)) + xlab('gene ix')

  )
}
```

## Compare original

```{r}
compare.data(degree.old_0.5, degree.new_0.5, random.sample)
```

## Same scale

```{r}
degree.old_0.5.scale <- degree.old_0.5 
degree.new_0.5.scale <- degree.new_0.5 / max(degree.new_0.5) * max(degree.old_0.5)

compare.data(degree.old_0.5.scale, degree.new_0.5.scale, random.sample)
```

## Mirror old and scale new

```{r}
degree.old_0.5.mirror <- max(degree.old_0.5.scale) - degree.old_0.5.scale
degree.new_0.5.mirror <- degree.new_0.5.scale

compare.data(degree.old_0.5.mirror, degree.new_0.5.mirror, random.sample)
```

## New transformed with 1 / value »» Same scale

```{r}
degree.old_0.5.scale.inv2 <- degree.old_0.5 
degree.new_0.5.scale.inv2 <- 1/ degree.new_0.5
degree.new_0.5.scale.inv2[is.infinite(degree.new_0.5.scale.inv2)] <- max(degree.new_0.5.scale.inv2[!is.infinite(degree.new_0.5.scale.inv2)])
degree.new_0.5.scale.inv2 <- degree.new_0.5.scale.inv2 / max(degree.new_0.5.scale.inv2) * max(degree.old_0.5.scale.inv2)
degree.new_0.5.scale.inv2 <- max(degree.new_0.5.scale.inv2) - degree.new_0.5.scale.inv2

compare.data(degree.old_0.5.scale.inv2, degree.new_0.5.scale.inv2, random.sample)
```

## Same scale (old transformed with 1/value)

```{r}
degree.old_0.5.scale.inv <- 1 / degree.old_0.5
degree.old_0.5.scale.inv[is.infinite(degree.old_0.5.scale.inv)] <- max(degree.old_0.5.scale.inv[!is.infinite(degree.old_0.5.scale.inv)])
degree.new_0.5.scale.inv <- degree.new_0.5 / max(degree.new_0.5) * max(degree.old_0.5.scale.inv)

compare.data(degree.old_0.5.scale.inv, degree.new_0.5.scale.inv, random.sample)
```

## Same scale (old transformed with log)

```{r}
degree.old_0.5.scale.inv <- log(1+degree.old_0.5)
degree.new_0.5.scale.inv <- degree.new_0.5 / max(degree.new_0.5) * max(degree.old_0.5.scale.inv)

compare.data(degree.old_0.5.scale.inv, degree.new_0.5.scale.inv, random.sample)
```
