---
title: "Example for Logistic Regularization"
author: "Vignette Author"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
params:
  seed: !r 29221
  some_string: "some string"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 6,
  fig.height = 8
)
```

```{r, include=FALSE, eval=FALSE}
rmarkdown::render('template.Rmd')
```


# Required Packages

*(AV: colocar todos pacotes necessários ao Rmd aqui)*

```{r libraries}
library(reshape2)
library(tidyverse)
library(glmnet)
library(survival)
library(futile.logger)
library(loose.rock)

#rmarkdown::render('template.Rmd')

library(parallel)
library(doMC)

# Load do package
devtools::load_all()

theme_set(theme_minimal())
.Last.value <- flog.layout(layout.format('[~l] ~m'))

.Last.value <- loose.rock::base.dir('./runcache')
.Last.value <- loose.rock::show.message(FALSE)
```

# Load data

```{r data}
# exemplo simples
my.data <- prepare.tcga.survival.data(project           = 'brca', 
                                      tissue.type       = 'primary.solid.tumor', 
                                      handle.duplicates = 'keep_first', 
                                      coding.genes      = TRUE)
xdata <- my.data$xdata
ydata <- my.data$ydata
```

# Build network penalization

```{r penalization}
# Random penalty vector
set.seed(params$seed)
penalty <- abs(rnorm(ncol(xdata)))
qplot(penalty, bins = 100)
```

# Fit models

```{r fit}
registerDoMC(cores=10)
fitted <- run.cache(cv.glmnet, 
                    xdata, Surv(ydata$time, ydata$status), 
                    family = 'cox', 
                    penalty.factor = penalty, parallel = TRUE,
                    seed = params$seed)
```

# Results of Cross Validation

```{r results}
plot(fitted)
```

## Using lambda.min taken from cross validation

```{r, echo=FALSE}
top.coefs <- coef(fitted, s = 'lambda.min')
coefs.v <- as.vector(top.coefs)
names(coefs.v) <- rownames(top.coefs)
flog.info('Non-zero coefficients:', coefs.v[coefs.v != 0], capture = T)
```

### Hallmarks of Cancer

```{r, echo=FALSE}
names.df <- gene.names(names(coefs.v[coefs.v != 0]))
all.hallmarks <- hallmarks(names.df$external_gene_name)

all.hallmarks$hallmarks$gene.name <- rownames(all.hallmarks$hallmarks)

melt(all.hallmarks$hallmarks, 
                  id.vars = c('gene.name')) %>% filter(value > 0) %>%
  ggplot(aes(gene.name,variable, fill=value)) + 
    geom_raster() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) + 
    ggtitle('Hallmarks heatmap', subtitle = sprintf('Genes without hallmarks (%d): %s', length(all.hallmarks$no.hallmakrs), paste(all.hallmarks$no.hallmakrs, collapse = ', '))) + 
    xlab('External Gene Name') + ylab('')
```

### Survival curves and Log rank test

```{r, echo=FALSE}
draw.kaplan(as.vector(coefs.v), xdata, ydata, filename = 'Full dataset', legend.outside = F)
```

